volumes:
  taski_static:
  taski_media:
  taski_pg_data:

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - taski_pg_data:/var/lib/postgresql/data

  backend:
    image: mak37/taski_backend:latest
    restart: always
    environment:
      DEBUG: "False"
      SECRET_KEY: "0SwsXC]xsd_&=^1tQ)wi23lo=7?LtqNgP!X5TQ>T^KxmILA/?-r+r%0-i$$aXzL]"
      ALLOWED_HOSTS: "tonali.mooo.com"
      CSRF_TRUSTED_ORIGINS: "https://tonali.mooo.com"

      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: django
      DB_USER: django_user
      DB_PASSWORD: mysecretpassword
      DB_HOST: db
      DB_PORT: "5432"

    volumes:
      - taski_media:/app/media
      - taski_static:/app/staticfiles

    depends_on:
      - db

  frontend:
    image: mak37/taski_frontend:latest
    volumes:
      - taski_static:/usr/share/nginx/html
    command: sh -c "cp -r /app/build/. /usr/share/nginx/html/"

  gateway:
    build: ./gateway
    image: mak37/taski_gateway:latest
    restart: always
    volumes:
      - taski_static:/usr/share/nginx/html
      - taski_media:/media
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
