version: '3.8'

volumes:
  taski_static:
  taski_media:
  taski_pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - taski_pg_data:/var/lib/postgresql/data

  backend:
    image: mak37/taski_backend:latest
    env_file: .env
    volumes:
      - taski_media:/app/media
      - taski_static:/app/staticfiles
    depends_on:
      - db

  frontend:
    image: mak37/taski_frontend:latest
    volumes:
      - taski_static:/static
    command: sh -c "cp -r /app/build/. /static/"

  gateway:
    build: ./gateway
    image: mak37/taski_gateway:latest
    volumes:
      - taski_static:/static
      - taski_media:/media
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
